version: "3.9"
services:
  core:
    image: "${IMAGE}"
    x-aws-pull_credentials: "${IMAGE_REPO_SM}"
    volumes:
      - core-data:/tg/data
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - API_PHONE_NUMBER
      - API_ID
      - API_HASH
    command: "scrape-groups --targets=\"${TG_GROUPS}\" -f ${FROM_DATE} -t ${TO_DATE} -v -u -b ${S3_BUCKET} -c"
volumes:
  core-data:
